name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: project-repo

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd project-repo
        npm ci

    - name: Build Hexo site
      run: |
        cd project-repo
        npx hexo generate

    - name: Checkout testing repo
      uses: actions/checkout@v4
      with:
        repository: yumis56/testing-repo
        path: testing-repo

    - name: Install Playwright
      run: |
        cd testing-repo
        npm ci
        npx playwright install

    - name: Run Playwright tests
      run: |
        cd testing-repo
        npx playwright test

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./project-repo/public
