name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    

    - name: Check for package.json
      run: |
        if [ ! -f package.json ]; then
          echo "package.json is missing!"
          exit 1
        fi
    
    - name: Build Hexo site
      run: |
        if [ ! -f _config.yml ]; then
          echo "_config.yml is missing!"
          exit 1
        fi
        
        docker build -t hexo-site . || { echo "Docker build failed"; exit 1; }
        
        docker ps -a
        
        docker run -t --name hexo-container hexo-site npm run build > build_output.log 2>&1 || { 
          echo "Build process failed. Container logs:"; 
          docker logs hexo-container;
          echo "Build output:";
          cat build_output.log;
          exit 1;
        }

        echo "Contents of /app directory:"
        docker exec hexo-container ls -la /app

        # docker exec hexo-container ls -la /app;
        docker cp hexo-container:/app/public ./public || { echo "Failed to copy files from container";  exit 1; }
        
        docker rm hexo-container
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hexo-site
        path: public

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build_output.log
        
    - name: Trigger tests
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: yumis56/testing-repo
        event-type: run-tests
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
